name: prime-public-testnet-tools-10_1_4

include:
  - docker-compose-core.yml
  - docker-compose-rosetta.yml

secrets:
  # prerequisite for: postgres, dbsync, blockfrost
  postgres_db:
    file: ./secrets/dbsync/postgres_db
  postgres_password:
    file: ./secrets/dbsync/postgres_password
  postgres_user:
    file: ./secrets/dbsync/postgres_user

volumes:
  # required for - prime-relay, dbsync, wallet-api, ogmios, submit-api
  #                use either as docker volume or if interracting from host over ipc commnet out and use local folder instead
  # node-ipc:
  # required for - prime-relay
  node-db:
  # required for - postgres
  postgres:
  # required for - dbsync
  db-sync-data:
  # required for - wallet-api
  wallet-api-data: